### ISSUE TITLE
Question: YAML file

### ISSUE THREAD

**Issue by arturek1666** [lucko/LuckPerms#1004]
Hi,

I have a small question so I always like to organize permissions like that:
```
#SuperVanish
- sv.use:
    value: true
- sv.list:
    value: true
- sv.login:
    value: true
- sv.logout:
    value: true
- sv.toggleitempickups:
    value: true
- sv.fly:
    value: true

#ChatControlNotify
- chatcontrol.notify.laggi:
    value: true
```

However when an permission is edited by the server or the website provided it will change to this and it will remove my comments and look like that: 
```
- preciousstones.whitelist.*
- epicspawners.silkdrop.*
- shopguiplus.shops.*
- essentials.warps.*
- essentials.world.*
- headdb.category.*
- authme.player.*
- modifyworld.*
- ChestShop.shop.*
- cmi.dropspawner.*
- pocketgames.game.*
- sticker.pack.foodpack.*
- artmap.artist
- artmap.artkit
- artmap.region.member
- autosmelt.mine
- betterrtp.use
- betterrtp.world.world
- bottledexp.interact
- bukkit.broadcast.user
```

As I like to edit stuff on website and sometimes on the minecraft server I still want to use it however because it just brakes my style and my comments it just get's not organized for me and just looks bad. Is there a way to fix that or not? I would love if that would work.
