### ISSUE TITLE
Console has no permission

### ISSUE THREAD

**Issue by Witchcrafter1** [lucko/LuckPerms#1044]
First Of: I know that sounds really weird, but I have the problem that the console cant executes some lp cmds. message: 
 [Info] [LP] You do not have permission to use this command!

Description:

When the bug happens, some cmd like 
/lp user [user] parent remove [group]
result in: 
 [Info] [LP] You do not have permission to use this command!

The problem: I executed the cmd in the console.

My Server:
![image](https://user-images.githubusercontent.com/37211601/41191502-e8538bd8-6bf0-11e8-88c2-bb735df5cb12.png)

a very new sponge version
newest luckperms

How to reproduce:

I think it is a problem with the argument based permission.

First, I have turned it to false
Cmds on console work

Then I turned it to true
and set up some permissions with arguments.
To understand my permission and groups:
I have a track with these groups:

helper, trial-mod, moderator, head-moderator, admin, head-admin, owner

each group has the others as parent

important are head-moderator with:
```
- luckperms.user.promote
- luckperms.user.promote.builder:
    value: false
- luckperms.user.promote.staff:
    value: false
- luckperms.user.promote.staffmember:
    value: false
- luckperms.user.promote.staffmember.helper

```
and admin with:

```
- luckperms.user.demote
- luckperms.user.demote.builder:
    value: false
- luckperms.user.demote.staff:
    value: false
- luckperms.user.promote.staffmember
```

Then the cmd doesn't work on the console.

If I turn the argument based permission now off
the cmds work

If you have any question, pls ask

**EDIT:
Ok in the newest version of the mod, it seems to be fixed**
