### ISSUE TITLE
Bug Report l storage-method = "yaml-combined"

### ISSUE THREAD

**Issue by RawrMaoster** [lucko/LuckPerms#1067]
Snippet of chat when i discovered this Bug:

> [5:47 AM] RawrMaoster: ok i got it to work i just didint give it a priority x-x altho { } i cant use :cry: there goes my cool prefixes
> [5:50 AM] RawrMaoster: Maybe you know why when i do [-{Owner}-] it displays as [--] deleting {Owner}
> [5:52 AM] Turbotailz: put it in "" ?
> [5:55 AM] RawrMaoster: Neither " " and ' ' work
> [5:56 AM] Turbotailz: ¯\_(ツ)_/¯
> [5:56 AM] RawrMaoster: shame
> [5:57 AM] RawrMaoster: i had pretty cool prefixes xD

So in summary, only because i dont use [Owner] like other servers i found a bug with how i display my groups when using the .yml configuration.

> [-(Owner)-] << Works - Normal Brackets (    ) << Output: [-{Owner}-]
> [-{Owner}-] << Breaks - Squiggly Brackets {    } << Output: [--]

So the Squiggly Brackets dont display with the text inside. So {Owner} Gets cut from the prefix in the chat on a live server.

groups.yml Example:    (Pretty much empty cause im slowly learning luckperms and 2 other plugins slowly)

```
owner:
  permissions:
  - displayname.[-{Owner}-]
  - nucleus.broadcast.
  prefixes:
  - '&4[-{&5Owner&4}-] &5':
      priority: 10
```
