### ISSUE TITLE
apply-bukkit-default-permissions doesnt affect

### ISSUE THREAD

**Issue by DrPanic** [lucko/LuckPerms#1092]
I have `apply-bukkit-default-permissions: true` in my Config but the default-permissions doesnt work anymore after the migration from PEX to LuckPerms.
What can i do?

LuckPerms v4.2.42

**Comment by Andre601** [comment]
According to the description does the `apply-bukkit-default-permissions:` (btw. GitHub uses Markdown in their issues, so [code][/code] won't work) only set, if permissions, that the plugin-author set for default (`default: <true/false/OP>` in the plugin.yml of the plugin.) should be applied or not.
https://github.com/lucko/LuckPerms/blob/da3c2a073a6bcdd7e29ec7ee2d6546fdc7c21f64/bukkit/src/main/resources/config.yml#L412-L418

I'm not sure, if that really is the case with your issue or not.
Also what "default-permission" do you mean?

**Comment by lucko** [comment]
Can you give an example, so I can look into it?

**Comment by DrPanic** [comment]
Sure, i noticed it with chestshop. In the plugin.yml is the following entry:
```
  ChestShop.shop.*:
    description: Gives access to all user ChestShop permissions
    children:
        ChestShop.shop.create: true
        ChestShop.shop.buy: true
        ChestShop.shop.sell: true
    default: true
```
The users couldn't create shops after the migration. When I gave permission to the permission-group, everything went back to normal behavior. It seems to be some other plugins which doesnt work with it.
