### ISSUE TITLE
FlatFile formatting improvements.

### ISSUE THREAD

**Issue by Zendrex** [lucko/LuckPerms#113]
I know this is more of a pet peeve than anything else, but the current way things such as prefix are setup as well as weight, etc are all clustered together under "perms" instead of somewhere that's easier and nicer to read.

Example:

Pex has it as such:
```
permissions:
    - '*'
    - permissions.*
inheritance:
    - Moderator
options:
    default: false
    prefix: '&3&lOWNER&r '
    suffix: '&3&lTEST&r '
worlds:
    World_Nether:
        permissions:
            - test.permissions1
            - test.permissions2
            - test.permissions3
```

How Luck has it set:
```
name: owner
perms:
    global-world_nether/group.moderator: true
    'prefix.0.&3&lOWNER&r ': true
    permissions.*: true
    'suffix.0.&3&lTEST&r ': true
    group.moderator: true
    '*': true
```

It would be nice if we could have a better formatted flat file instead of the "cramped" system there is now. Would make reading through everything much easier too among other things. If there is any specific reason why it is formatted the way it is as of now, I would like to know why, and if there is any possibility for it to get a "better looking" format.
