### ISSUE TITLE
Issue: LuckPerms placeholders don't seem to be working

### ISSUE THREAD

**Issue by redstonedesigner** [lucko/LuckPerms#1137]
Title says it all.
I am trying to stack prefixes (staff, donator etc.), but it isn't working.
I have the latest PAPI extension (v4.1) and I don't quite know what the problem is.

If someone could let me know what I am doing wrong, that would be excellent.
Thanks,
[@redstonedesigner](https://github.com/redstonedesigner)

**Comment by Zimon4eR** [comment]
Isn't latest PAPI is 4.5.1?
https://github.com/rojo8399/PlaceholderAPI/releases

**Comment by redstonedesigner** [comment]
It's not the PAPI version, it's the LP extension version.

**Comment by redstonedesigner** [comment]
And also, that's for SpongeAPI, not Spigot.

**Comment by Imortalshard** [comment]
What placeholders are you using exactly and how have you got it set up in the LuckPerms config?

**Comment by redstonedesigner** [comment]
I'm trying to use `%luckperms_prefix%` in DeluxeChat.
Related config:
```
meta-formatting:
  prefix:
    format:
    - "highest_on_track_donator"
    - "highest_on_track_staff"
    - "highest_on_track_yt
    - "highest_on_track_dev"
    - "highest_on_track_builder"
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
  suffix:
    format:
      - "highest"
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
```
