### ISSUE TITLE
Permission for the main luckperms command

### ISSUE THREAD

**Issue by LogGits** [lucko/LuckPerms#1310]
1.13 puts this command into tab-complete for players who wouldn't use it nor have any permissions for luckperms. Im trying to seperate all admin commands from regular player commands. 

Something like `luckperms.help` would be helpful for resolving this. Setup in a similar format to:
```yaml
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: true
```
