### ISSUE TITLE
Argument based command permissions only working for some things

### ISSUE THREAD

**Issue by FrozenBeard** [lucko/LuckPerms#1401]
I have Argument based command permissions working for one set of permissions for staff, they can add parent for a specific group, but they are refused to addtemp parent, this was working at one point, I cant see whats wrong here, I even tried verbose and it suggested  `luckperms.user.parent.addtemp` in general, but I added this and it didnt work.

```
- luckperms.user.parent.addtemp.privateer:
    world: PirateCraft_1
    value: true
- luckperms.user.parent.removetemp.privateer:
    world: PirateCraft_1
    value: true
- luckperms.user.parent.remove.privateer:
    world: PirateCraft_1
    value: true
- luckperms.user.parent.add.privateer:
    world: PirateCraft_1
    value: true
```
The parent add works but the addtemp does not how comes?

Verbose for just me: https://luckperms.github.io/verbose/#KHn5HuiV6i
