### ISSUE TITLE
LP Editor fails to connect to ByteBin during group edits.

### ISSUE THREAD

**Issue by TheFlagCourier** [lucko/LuckPerms#1435]
So the issue here seems to be that when adding multiple permissions at a time, the editor will trigger this failure. The log snippet shows a successful use of the editor, when addding a test permission, but then a failed use when editing a group.

_LP Info_
Java: OpenJDK 11.0.1
```yaml
Running LuckPerms v4.3.94 by Luck.
 Platform: Bukkit
 Server Brand: Paper
 Server Version: git-Paper-524 (MC: 1.13.2) - 1.13.2-R0.1-SNAPSHOT
 Storage:
    Type: MariaDB
    Ping: 0ms
    Connected: true
 Messaging: Sql
 Instance:
    Static contexts: None
    Online Players: 1 (1 unique)
    Uptime: 1h 24m 21s
    Local Data: 1 users, 19 groups, 2 tracks
```

_Console Log_
https://gist.github.com/TheFlagCourier/cd38fbf3a74ceab5bb2dc89152bef1a9

Before Adding Perms
![part1](https://user-images.githubusercontent.com/2712890/52919391-b51d7c80-32c7-11e9-886a-c0125dae856c.png)

After Adding Perms
![part2](https://user-images.githubusercontent.com/2712890/52919392-b64ea980-32c7-11e9-8cc1-037d05bf7fbf.png)
