### ISSUE TITLE
Migration from PEX: default group

### ISSUE THREAD

**Issue by x1p** [lucko/LuckPerms#1501]
I'm testing migration of PEX
I see the following:
PEX:
```
  rank-a:
    options:
      default: true
      prefix: '&a'
    permissions:
    - blah
```
Is being translated into LP like:
default.yml
(empty file)
rank-a.yml
```
name: rank-a
permissions:
- blah
meta:
- default:
    value: 'true'
```
I wonder why LP would not prefer to make a default.yml, place the rank-a permissions into this one and make this default rank have a displayname "rank-a"

I think this will make migration a lot more simple for people just starting with LP, like me ;-)
If this is intentional, I would like to learn the strategy behind it.
