### ISSUE TITLE
MySQL attempts to connect to a completely different MySQL Server

### ISSUE THREAD

**Issue by DieselGaming** [lucko/LuckPerms#1718]
Sooo, I enter my MySQL Details into the config.
It ends up looking like this:
```
data:

  # Define the address and port for the database.
  # - The standard DB engine port is used by default
  #   (MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017)
  # - Specify as "host:port" if differs
  address: "69.super.kewl.ip"

  # The name of the database to store LuckPerms data in.
  # - This must be created already. Don't worry about this setting if you're using MongoDB.
  database: dieselg_perms

  # Credentials for the database.
  username: dieselg_lperms
  password: 'sup3raw3s0m3Pa55w0rd'
```
And when starting up it is connecting to this address:
```
static.58.36.202.116.clients.your-server.de
```
Sooooo yeah.
