### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by MajorLOLGaming** [lucko/LuckPerms#1761]
hey, so i have my ranks setup so that my ranks (OG, YT, and coowner), and they display like so: "**[OG] [YT] [CO] Major**". Now, my players, who dont have any ranks other than "User", should have a tag, saying "[U]", but they dont. and if i add the user rank to one of my tracks, the other users, who do have other ranks, will have the "[U]" show up, when it shouldnt. My config is:
```
prefix:
    format:
      - "highest_on_track_extra"
      - "highest_on_track_perks"
      - "highest_on_track_ranks"
      - "highest_on_track_staff"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: " "
```

Extra: OG
Perks: YT
Ranks: vip -> mvp -> premium -> legendary -> overlord
Staff: builder -> helper -> mod -> headmod -> admin -> headadmin -> coowner -> owner

Not in a track: default (User)

How do i make it so that the user rank shows up on users, and not other players?
