### ISSUE TITLE
SUGGESTION: SetTemp for Default Assignments/Rules

### ISSUE THREAD

**Issue by TheOnlyMaldred** [lucko/LuckPerms#1762]
Can we please get an option for setting temporary groups to users upon joining from the config file?

Example of what it could look like:
```
default-assignments:
  my-defaults-rule:
    if:
      has-true: <group.default>
    take:
      - group.default
    give:
      - group.member 24d12h6m
    set-primary-group: member
```
