### ISSUE TITLE
Luckperms SQL Error | redirected to git hub

### ISSUE THREAD

**Issue by aidplasss** [lucko/LuckPerms#2096]
So I get this error spammed in the console:
WARN: Establishing SSL connection without server's identity verification is not recommended.  ect ect

However, my pool settings seem to be correct?
```
  pool-settings:
    # This setting allows you to define extra properties for connections.
    properties:
      useUnicode: true
      characterEncoding: utf8
      useSSL: false
      verifyServerCertificate: false
```
I was told to redirect to github and make an issue thingy here!
