### ISSUE TITLE
New flatfile schemas

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#211]
I want to change the file formats used by the YAML and JSON storage types.

The current system is very simple, but gets really messy when you have permissions with custom contexts attached.

The new layout I propose is as follows. It follows the same layout between JSON and YAML as before, with only changes in syntax.

### JSON
```json
{
    "name": "Luck",
    "uuid": "--uuid-goes-here--",
    "primaryGroup": "default",
    "permissions": {
        "some.permission": {
            "value": true
        },
        "some.other.permission": {
            "value": true,
            "server": "factions"
        },
        "some.other.permission.thing": {
            "value": true,
            "server": "factions",
            "context": {
                "gp_claim_defaults": ["WILDERNESS"]
            }
        }
    }
}
```

### YAML
```yaml
name: Luck
uuid: --uuid-goes-here--
primaryGroup: default
permissions:
  - some.permission:
      value: true
  - some.other.permission:
      value: true
      server: factions
  - some.other.permission.thing:
      value: true
      server: factions
      context:
        gp_claim_defaults:
          - WILDERNESS
```

Any comments / ideas are welcome.
