### ISSUE TITLE
Add support for TLS with Redis 6

### ISSUE THREAD

**Issue by Govindass** [lucko/LuckPerms#2263]
Redis 6 adds support for TLS, but LuckPerms fails to load with it (need to set SSL to true in jedis connections), I had to switch to plugin messaging temporarily. This will also require updating jedis dependency to 3.3.0

**Comment by lucko** [comment]
You'll need to add the ssl property to your config:

```yaml
redis:
  enabled: true
  address: localhost
  password: 'example'
  ssl: true
```
