### ISSUE TITLE
PAPI with ExtraContext crashes server 

### ISSUE THREAD

**Issue by SLASHLogin** [lucko/LuckPerms#2446]
Using 
```
placeholderapi: true
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
  god: "%luckperms_check_permission_essentials.god.others%"
```
in extracontext causes server to crash whenever luckperm tries to calculate player. 
allowflight works and does not produce this bug.

Version: 1.16
LP: 5.1.26

https://pastebin.com/NLZ8z1iY
