### ISSUE TITLE
Primary groups does not take context

### ISSUE THREAD

**Issue by Rakdos8** [lucko/LuckPerms#2459]
Hi there,

I ran into an issue (I think ?) or it behave weirdly. I've created 2 other groups: `citizens` and `staff-context` to keep the track as : `default` > `citizens` > `staff-context`
cf:
![group parents](https://user-images.githubusercontent.com/22244611/87422488-fc04c400-c5d8-11ea-94b2-b4cc318bf052.png)

Then I try to `/lp user bathman18 parent set staff-context server=skyblock` but it looks like LuckPerms consider that `bathman18` lost his primary group and add `default` back. But LuckPerms consider the context to be matching and print his prefix and so on.
Yet, his prefix does not apply in game.
![After set parent](https://user-images.githubusercontent.com/22244611/87422675-59991080-c5d9-11ea-9738-64e7da69c919.png)
I've run a verbose here:
![Verbose](https://user-images.githubusercontent.com/22244611/87422780-86e5be80-c5d9-11ea-801b-e3e03466d5fa.png)
![Verbose details](https://user-images.githubusercontent.com/22244611/87422782-8816eb80-c5d9-11ea-81ce-16575c40c443.png)

Yet, if I remove the context `server=skyblock` for `bathman18` it looks like the group is applied correctly and prefix is attached as well
![After set parent 2](https://user-images.githubusercontent.com/22244611/87422856-abda3180-c5d9-11ea-9f45-4fe92342f780.png)

I thought I was running the same issue as https://github.com/lucko/LuckPerms/issues/2270 but here is my `config.yml`:
```yaml
server: skyblock
include-global: true
include-global-world: true
apply-global-groups: true
apply-global-world-groups: true

primary-group-calculation: all-parents-by-weight # I've also tried parents-by-weight with no success
meta-value-selection-default: highest-number # I've tried inheritance with no success
```

The idea below that is to have one staff per server and not sharing permissions all around.

Thank you :)

PS: The 2nd example is strictly what we're looking for: https://github.com/lucko/LuckPerms/wiki/Advanced-Setup

**Comment by Rakdos8** [comment]
But if I replace the `server: skyblock` into `server: global` from the `config.yml` and define a `static-context`:
```json
{
  "static-contexts": {
    "server": "skyblock"
  },
  "default-contexts": {}
}
```

It looksl ike LuckPerms take, correctly, in account the primary group
![context global](https://user-images.githubusercontent.com/22244611/87424591-84389880-c5dc-11ea-9c87-326f8bf125b0.png)

**Comment by benwoo1110** [comment]
You should not need to touch context.json at all. Just base your context on servername defined in `server: servername` in LP config.yml for all backend servers.

**Comment by Rakdos8** [comment]
> You should not need to touch context.json at all. Just base your context on servername defined in `server: servername` in LP config.yml for all backend servers.

Exactly, but when I put the `server: server-name` it does not take in account the true primary group so what am I missing ?

**Comment by benwoo1110** [comment]
The prefix as well as the primary group is correct in `lp user USER info` tho. Ensure you have vault plugin if you are displaying either using another plugin

**Comment by Rakdos8** [comment]
I'm using `Vault` (1.7.2) and `EssentialsXChat` (2.17.2.117)

**Comment by benwoo1110** [comment]
The thing is the prefix as well as the  primary group is the same regardless of the context. So I doubt its due to the context. Screenshot `lp user USER meta info`

**Comment by BrainStone** [comment]
Have you looked at the issue Ben?

It's full of those screenshots...

**Comment by BrainStone** [comment]
Oh. My bad I missed the `meta` in the command.

**Comment by Rakdos8** [comment]
Here is `/vault-info` suggested in the wiki:
![vault-info](https://user-images.githubusercontent.com/22244611/87426175-1cd01800-c5df-11ea-80c2-36b4acd94410.png)

And the meta info `lp user USER meta info`:
![meta-info](https://user-images.githubusercontent.com/22244611/87426179-1d68ae80-c5df-11ea-98be-990f1c65a8f1.png)

**Comment by Rakdos8** [comment]
I can dump the database (MySQL) if you want to give a try

**Comment by Rakdos8** [comment]
Dump.
Any news on this ?

**Comment by lucko** [comment]
Will need to look into this in a bit more detail - very limited on time at the moment but I'll try get to it soon.

**Comment by BrainStone** [comment]
I’d like to add that this also appears to affect prefixes. Using the trick with the static contexts fixed that too.

**Comment by Rakdos8** [comment]
> I’d like to add that this also appears to affect prefixes. Using the trick with the static contexts fixed that too.

Permissions are also affected if I remember well.
Also, if I define a static context and keep the `server: server-name` in the `config.yml` it won't work unless I set it to `server: global`

**Comment by Rakdos8** [comment]
Any idea on when it will be fixed or looking for resolution ?

**Comment by TheWackersKian** [comment]
I am experiencing this same issue, glad to know I'm not the only one.

**Comment by TheWackersKian** [comment]
Please fix this issue as it still doesn't work.

**Comment by Rakdos8** [comment]
Any update since ?

**Comment by Rakdos8** [comment]
It's been 2 months now. Can I do anything to help fixing this issue ?

**Comment by Rakdos8** [comment]
Actually, looks like the latest version (`5.1.107`) solves the issue.
I can only hope that you know what you've done to fix this issue which won't happen next time ;)

**Comment by TheWackersKian** [comment]
This still doesn't work for me. I'm fully updated too

**Comment by Rakdos8** [comment]
Have you tried the `5.1.107` version ?
Also, we might have changed some default config values such as :
```yaml
primary-group-calculation: all-parents-by-weight

inheritance-traversal-algorithm: depth-first-pre-order

context-satisfy-mode: at-least-one-value-per-key

include-global: true
include-global-world: true
apply-global-groups: true
apply-global-world-groups: true

meta-value-selection-default: highest-number
```
