### ISSUE TITLE
[bug] 919 Errors Using Export/Import to move from Yaml to Mysql for user storage

### ISSUE THREAD

**Issue by FrozenBeard** [lucko/LuckPerms#246]
I was using Yaml storage for everything and wanted just my users in MySQL, Using the MariaDB driver. To do this, I used the export feature, stopped the server, changed the split storage type to mariadb for "users" then ran the import. The database populated with the users ranks, but there was a massive 919 error message that has got me worried. Some users have specific permissions (1 or two) and multiple ranks that I don't want to have to deal with lost ranks in converting form yaml to mysql.
So to be safe, lets figure out why this happened. 

My Settings:
```
storage-method: yaml
watch-files: true

split-storage:
  enabled: true
  methods:
    user: mariadb
    group: yaml
    track: yaml
    uuid: yaml
    log: yaml
```

A zerobin of the errors, as I hit the max with pastebin!

https://zerobin.net/?a43d961754577fcb#FZ7hMM6/uPH6M66Dmj3RsVXoYkmDwNG2dVxrGiQLh9U=

My theory is that its attempting to import the permissions I have setup, but since its disabled in the split-storage, as I already have the yaml files with permissions existing already, its throwing errors as the export exports all data not just the users, like im doing in this example. So when I import its getting stuck as my permissions are already yaml and exist!
