### ISSUE TITLE
[Bug] SQL error - Connection is not available, request timed out after 5001ms.

### ISSUE THREAD

**Issue by momoservertw** [lucko/LuckPerms#2539]
I get error messages while starting the server.
There is about a 30% chance of restarting without showing errors.

This is the error messages.
https://pastebin.com/fnYUjWWT

Please help me :'(
```
pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000
    connection-timeout: 5000
    properties:
      useUnicode: true
      characterEncoding: utf8
      useSSL: false
```

Paper version: git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) (Latest)
Luckperms version: 5.1.86 (Latest)
MySQL version: 8.0.12 MySQL community server - GPL
