### ISSUE TITLE
Per world default groups

### ISSUE THREAD

**Issue by ChickenPillow** [lucko/LuckPerms#259]
Is it possible to set per world (multiverse) default groups?

I know you can do per server like this:
```

default-assignments:
  my-defaults-rule:
    if:
      has-true: <factions/group.default>
    take:
      - factions/group.default
    give:
      - factions/group.member
    set-primary-group: member
```

but how about per world would it be like this:

```
default-assignments:
  my-defaults-rule:
    if:
      has-true: <world.factions/group.default>
    take:
      - world.factions/group.default
    give:
      - world.factions/group.member
    set-primary-group: member

```
Thanks

- ChickenPillow
