### ISSUE TITLE
Stacking prefix won't work!

### ISSUE THREAD

**Issue by Alexx-gh** [lucko/LuckPerms#2648]
**Description**
Stacking prefixes won't work; unable to get more than one prefix to show.
*No errors show up*

**Environment details**
Server type/version: Paper 1.16.3
LuckPerms version: v5.1.107

**Config**
```
prefix:
  format:
    - "highest_on_track_person"
    - "highest_on_track_staff"
    - "highest_on_track_normal"
  duplicates: first-only
  start-spacer: "★ "
  middle-spacer: " | "
  end-spacer: " "
```

**Editor**
https://luckperms.net/editor/B01icB17I2
**Chat example.**
https://i.imgur.com/eA3Wb4W.png
**User Info**
https://i.imgur.com/QM7UceP.png
