### ISSUE TITLE
Luckperms Bungee not working

### ISSUE THREAD

**Issue by izakhearn** [lucko/LuckPerms#342]
Hey after updating to the latest bungeecord and luckperms version no permissions on the bugeecord side wants to work here is my start up log https://gist.github.com/izakhearn/1acec29b953040f5ca9deeff5c8dd74d

**Comment by lucko** [comment]
What's not working about it?

**Comment by izakhearn** [comment]
Yes it does but none of my perms i gave works like my slashsever perm my bungee command perms they dont work. I made sure that my permission nodes are correct and checked that i am in the luckperms group
but to no luck it does not work and that is the only plugin that is a permission management plugin on the whole bungee. I will try removing all the plugins on bungee again and check again.

**Comment by lucko** [comment]
Can you pastebin your config file, and screenshot the output to "/lpb user <you> permission info".

**Comment by izakhearn** [comment]
Will do 
![image](https://user-images.githubusercontent.com/25284121/27644235-420e0ce0-5c23-11e7-9438-cc45025af11a.png)
and then 
https://gist.github.com/izakhearn/ac450e5b3e2d8133e71bd7dd8d0d1246

**Comment by izakhearn** [comment]
this is for the owner group 
![image](https://user-images.githubusercontent.com/25284121/27644453-e5d41ac2-5c23-11e7-8623-cdef8878cf82.png)

**Comment by lucko** [comment]
```yaml
# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: global

# If users on this server should have their global permissions applied.
# If set to false, only server specific permissions will apply for users on this server
include-global: false
```

... meaning, no permissions will be applied. :)

You need to set include-global to true.
