### ISSUE TITLE
[Suggestion] group permission info aliases

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#473]
Dear,

Could you add `list` as aliases of /lp group <group> permission info? Maybe also for /lp user <user> permission info.

If you're going to change it, maybe it will break https://github.com/lucko/LuckPerms/issues/461 would be amazing if you can let both works.

**Comment by spannerman79** [comment]
> Could you add list as aliases of /lp group permission info? Maybe also for /lp user permission info.

Do it yourself https://bukkit.gamepedia.com/Commands.yml

**Comment by lucko** [comment]
I think that's a bit beyond the scope of what Bukkit can do @spannerman79 .

**Comment by spannerman79** [comment]
Actually it isn't @lucko 
```
aliases:
    list:
    - "lp user $$1 permission info"
    listg:
    - "lp group $$1 permission info"
```

`list` & `listg` can be subbed with anything you want or what isn't already taken.
