### ISSUE TITLE
Primary group does not set back to another parent group when the group is removed.

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#506]
LuckPerms dev 358

```/lp user <user> switchprimarygroup admin```
```/lp user <user> switchprimarygroup donor```
```/lp user <user> info```

Will show the user's primary group as donor with a parent group of admin and donor.

```/lp user <user> parent remove donor```
```/lp user <user> info```
Will still show the user's primary group as donor while parent group only displays as admin. This also makes it so the player shows up in /list as donor instead of admin even though they don't have the rank.

Would it be possible to use the user's last group as the new primary if they no longer have permission for that parent group? i.e. only displaying groups / primary prefix for ranks they actually have.

---

With PEX,

```/pex user <user> group set admin```

```
  uuid-string-blablabla:
    group:
    - admin
    options:
      name: player
```

Player talks, has admin prefix.

```/pex user <user> group add donor```

Add command always sets the last group on top as primary.
```
  uuid-string-blablabla:
    group:
    - donor
    - admin
    options:
      name: player
```

Player talks, has donor prefix.

``````/pex user <user> group remove donor``````
```
  uuid-string-blablabla:
    group:
    - admin
    options:
      name: player
```

Player talks, has admin prefix again.
