### ISSUE TITLE
Allow primary group to be set when adding groups.

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#507]
LuckPerms dev 358

LuckyPerms does not seem to adjust player primary group when adding groups via ```/lp user <user> parent add <group>```.  Would it be possible to have a config option to allow primary groups to be set on top when adding groups to a player?

---

With PEX.

User has 3 groups. When they chat, it uses the legendary tag.
```
  uuid-string-blablabla:
    group:
    - Legendary
    - Builder
    - Member
    options:
      name: player
```

```/pex user <user> group add Test```

```
  uuid-string-blablabla:
    group:
    - Test
    - Legendary
    - Builder
    - Member
    options:
      name: player
```

User was given the group Test. It is now set on top of their groups as their primary group and uses the prefix from Test.
