### ISSUE TITLE
Warn in console when using MySQL

### ISSUE THREAD

**Issue by weaves7** [lucko/LuckPerms#599]
Just started setting up LuckPerms for my bungee network with MySQL after using Pex (not with MySQL though) for years. So i am not familar with LP yet, so sorry if i am just missing something. But i get this warning on startup. 

10.12 18:07:07 [Server] WARN Sun Dec 10 18:07:07 EST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by spannerman79** [comment]
If you searched the issue tracker you would have came across this https://github.com/lucko/LuckPerms/issues/285#issuecomment-301232140

**Comment by weaves7** [comment]
Sorry, when I looked at the issues I forgot about the "is:open" filter. Also I did some more research and found that if I added the following it would no longer have the warning. This may help  others looking for a fix.

Note the placement of "?useSSL=FALSE"
```
data:
  #Uses standard DB engine port by default
  #MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017
  #Specify as "host:port" if differs
  address: 0.0.0.0

  database: mydatabase?useSSL=false
  username: myusername
  password: mypassword
```

**Comment by lucko** [comment]
The correct fix for this is to specify a property.

```yaml
data:
  pool-settings:
    # This setting allows you to define extra properties for connections.
    properties:
      useSSL: false
```
