### ISSUE TITLE
Config option to choose between depth-first and breadth-first inheritance resolution

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#719]
LuckPerms-Bukkit-4.0.117 (dev 516)
Paper dev 1317 (Spigot 1.12.2)

@lucko Global permissions seem to have a higher priority than individual world ones. I have a group that is given worldedit permissions. These permissions are given globally so they can use worldedit in any world. I also negate the worldedit permissions in a specific world with a wildcard because I do not want those players to be able to use worldedit in that world. However, they are still able to make a selection with the worldedit wand, as well as use worldedit commands (i.e. ```/cut```) in that world.

LP verbose reports they still have permission to use that worldedit command / utility. Thus this leads me to believe that the global inherited permissions are receiving a higher priority over individual world defined ones.

Group permissions.
https://paste.ubuntu.com/26468886/

**Comment by BrainStone** [comment]
Specific permissions override wildcard permissions. See this page for all details: https://github.com/lucko/LuckPerms/wiki/Advanced-Setup#permission-calculation

**Comment by mibby** [comment]
So world permissions will override generic permissions, but not in the case of if the world permission is a wildcard and the generic one isn't? Hmm.

**Comment by BrainStone** [comment]
That is correct. As generic permissions always take priority.
The page I liked explains it in detail and what other factors play in

**Comment by mibby** [comment]
@BrainStone I see, thanks for explaining. I guess I'll have to not use a wildcard to bulk negate in individual worlds then.

However I seem to be running into another issue. Are permissions given higher up in the inheritance tree not taking priority / overriding lower rank ones?

Member rank has the following permission.
```
name: member
permissions:
- essentials.build:
    value: false
    world: experimental
- mcmmo.ability.acrobatics.gracefulroll:
    value: false
- mcmmo.ability.axes.skullsplitter:
    value: false
- mcmmo.ability.blastmining.all:
    value: false
- mcmmo.ability.excavation.gigadrillbreaker:
    value: false
- mcmmo.ability.herbalism.greenterra:
    value: false
- mcmmo.ability.mining.blastmining.all:
    value: false
- mcmmo.ability.mining.superbreaker:
    value: false
- mcmmo.ability.swords.serratedstrikes:
    value: false
- mcmmo.ability.unarmed.berserk:
    value: false
- mcmmo.ability.unarmed.blockcracker:
    value: false
- mcmmo.ability.woodcutting.treefeller:
    value: false
- meta.weight.15
- weight.5
```

Donor rank has the following permission. Inheriting member rank for 'default' permissions.
```
name: donor
permissions:
- essentials.build:
    value: true
    world: experimental
- mcmmo.ability.acrobatics.gracefulroll:
    value: true
    world: experimental
- mcmmo.ability.axes.skullsplitter:
    value: true
    world: experimental
- mcmmo.ability.blastmining.all:
    value: true
    world: experimental
- mcmmo.ability.excavation.gigadrillbreaker:
    value: true
    world: experimental
- mcmmo.ability.herbalism.greenterra:
    value: true
    world: experimental
- mcmmo.ability.mining.blastmining.all:
    value: true
    world: experimental
- mcmmo.ability.mining.superbreaker:
    value: true
    world: experimental
- mcmmo.ability.swords.serratedstrikes:
    value: true
    world: experimental
- mcmmo.ability.unarmed.berserk:
    value: true
    world: experimental
- mcmmo.ability.unarmed.blockcracker:
    value: true
    world: experimental
- mcmmo.ability.woodcutting.treefeller:
    value: true
    world: experimental
- group.member
- weight.5
- meta.weight.15
parents:
- member
```

Builder rank has the following permissions. Inheriting member rank for 'default' permissions.
```
name: builder
permissions:
- meta.weight.15
- weight.5
parents:
- member
```

* If a person is only ranked ```member```, they can not use mcmmo abilities or build in the world ```experimental```. 
* If a person is only ranked ```donor```, they can build in the ```experimental``` world and use mcmmo abilities there.
* If a person is ranked ```donor``` and ```builder``` and has ```donor``` set as their primary group, they can build and use abilities.
* If a person is ranked ```donor``` and ```builder``` and has ```builder``` set as their primary group, **they cannot build or use abilities.** Despite the donor rank giving permission.

My rank tree looks like this.
Member
Member -> Donor1 -> Donor2 -> Donor3
Member -> Builder1 -> Builder2 -> Builder3

Players can have only one or both a donor and builder rank. Those rank trees inherit member rank as a fallback to ensure they have default permissions in case they get set to the rank and no longer have member as part of their grouping. Players are allowed to ```switchprimarygroup``` their groups to have a primary group set for color and prefix of their choice. (i.e. displaying builder prefix instead of donor). However if they have a builder rank set as their primary group, the permissions granted to donor to override negation in member no longer take effect.

I match the weight values so one rank prefix doesn't take priority over another and is instead displayed based on what the person's primary group is set to. As well
