### ISSUE TITLE
[question] EssentialsX - list primary group issue	

### ISSUE THREAD

**Issue by TheoRetisch1** [lucko/LuckPerms#837]
I am using EssentialsX and most of the player and staff member use the /list command frequently. Unfortunatly the list-command displays the parent group instead of the primary group quite often. I have serveral primary groups listed in the essentials config and also several parents, but I have only issues with one parent called „Spender“. The only difference between the parents is that the parent „Spender“ has a suffix in the chat displayed with ChatControl. The real reason why I cant figure out the issue is that the problem appears often but not always. It seems like the plugin can´t find the primary group after an server restart anymore. So in order to clarify the statement: Using /list I want the player to be displayed with their primary group but never with their parent. I use „/lp user xy parent add Spender“ in order to assign a new parent to a player.
I appreciate any help you can provide 😊

LP-info of a player who has the parent „Spender“ and is displayed correctly: https://imgur.com/a/qeXLQ
LP-info of a player who has the parent „Spender“ and isn´t displayed correctly: https://imgur.com/a/Xtq4I

Vault: v1.6.1
LuckPerms: v4.1.25
1.12.2 PaperSpigiot: 1349
EssentialsX: 2.01.-bSNAPSHOT 
ChatControl: 7.8.1

Vault-info:
```
 [Server thread/INFO]: [Vault] Vault v1.6.1 Information
 [Server thread/INFO]: [Vault] Economy: Craftconomy3 [LuckPerms]
 [Server thread/INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
 [Server thread/INFO]: [Vault] Chat: LuckPerms [LuckPerms]
```

ChatControl config:
```
spender_abzeichen:
      Message: '&9[$]&r '
      Sender_Permission: chatcontrol.groups.spender
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '{corpchanger_secondary_color}&m                    &r {corpchanger_primary_color}&lSpender&r
          {corpchanger_secondary_color}&m                   &r'
        - ''
        - '   {corpchanger_primary_color}&lCorp &9bedankt sich bei &f&l{essentials_nickname}'
        - '          &9für die liebe Spende!'
        - ''
        - '{corpchanger_secondary_color}&l>> {corpchanger_primary_color}Klick für
          Infos zu Spenden'
      Click_Event:
        Action: OPEN_URL
```
EssentialsX config: 
```
    Admin: admin
    Supporter: supporter
    Officer: Officer
    Stift: stift
    Azubi: azubi
    Journalist: journalist
    Baumeister: baumeister
    Urgestein: urgestein
    Legende: legende
    Elite: elite
    Super-Member: supermember
    Ehren-Member: ehrenmember
    Pro-Member: promember
    Member: member
    Gast: default
    Mulch: mulch
    Tourist: tourist
```
