### ISSUE TITLE
GroupManager migration issue

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#883]
When migration from group manager the username in the luckperms_player will be always null.
But in the groupmanager user.yml config there is a key called `lastname `, it would be great if that key can be used if it's present.

Example
```
  34a444ce-6b4b-3f1e-8b2c-23294f653cd4:
    lastname: voodootje0
    group: Owner
    subgroups: []
    permissions: []
```
