### ISSUE TITLE
Do not apply in "world"

### ISSUE THREAD

**Issue by k0nker** [lucko/LuckPerms#990]
I'm having a hard time figuring out how to do something and I am not sure it's entirely possible without a ton of context usage which negates the promote option which would make tracks useless for me.

I want to put a user in a group when they're in a certain world and have it revoke their perms from the other group entirely.

Essentially I have two tracks that players follow: rank and skyrank.  When a player is in ANY world other than skyworld, I want the normal group that's in the rank track to apply to them.  This rank group often has MANY perms that the groups in the skyrank track do not have.  I have the skytier1 set with context world=skyworld, and ranktier1 as a global parent.

Example of what I have tried regarding perms:

`
name: ranktier1
permissions:
- group.ranktier1perms
`
`
name: skytier1
permissions:
- group.ranktier1perms:
    value: false
`
However  when the context is met (the player is in world=skyworld) it does not remove the group.ranktier1perms from the player.  From what I read of the advanced config file the world perm should override general/global perms.  If I specifically add something like essentials.fly and put it to false that removes it, though it doesn't seem to treat groups of perms the same.

Am I missing something or is this intended not to work?

**Comment by Phyther** [comment]
Why not assign both groups to the players, then have the permissions themselves be world-specific?
```
permissions:
 - group.ranktier1perms:
     value: true
     world: [your world]
```
If you set the world context to the permissions instead of the groups, then you could set global permissions with deny on certain worlds...

**Comment by k0nker** [comment]
With 15 worlds that is 14 extra tags for each permission that is active on all worlds except for skyworld. While that would allow for promote/demote to work, it doesn't address the issue where group.nameofgroup set to false on a world perm is not working as other perms listed to false in that context are.

**Comment by k0nker** [comment]
I managed to accomplish the exclusion of a world by changing the config file aliases.  I set all worlds to have the alias "normalranks" except for skyworld.  Accomplishes what I've set out to do, though I still believe adding a !worldname option would be a cleaner execution.

**Comment by lucko** [comment]
It's not really possible to add negated contexts.

The whole concept of contexts is deeply embedded within LuckPerms, and other systems within the plugin (and other plugins depending on LP) rely on the behaviour of it.

See: 

https://github.com/lucko/LuckPerms/tree/master/api/src/main/java/me/lucko/luckperms/api/context
https://github.com/SpongePowered/SpongeAPI/tree/bleeding/src/main/java/org/spongepowered/api/service/context

I'm not sure what you mean re: the bug with aliases.

Prefixes should work fine (although that depends on how they're resolved) - the resolution of aliases happens before prefixes are queried, so nothing special has to happen there.

Weights can't be set in specific contexts, so I'm unsure what you mean by that.

(also sorry for the late reply, I've had a busy week 😢 )

**Comment by k0nker** [comment]
Thanks for the clarification on world!= context.

As for aliases, I meant the world rewrite "aliases".

From config.yml:
```
# Allows you to set "aliases" for the worlds sent forward for context calculation.
#
# - These aliases are provided in addition to the real world name. Applied recursively.
# - Remove the comment characters for the default aliases to apply.
world-rewrite:
  new_nether: normal
  new_the_end: normal
  new: normal
  survival_the_end: normal
  survival_nether: normal
  survival: normal
  creative: normal
  games: normal
  world: sky
  world_nether: sky
  world_the_end: sky
```

When using those as context it works fine for permissions within groups.
Like:
![2018-05-13 14_09_32-window](https://user-images.githubusercontent.com/6345469/39970785-5446507c-56b7-11e8-9ca8-3c2586a71e22.png)

However when the same context is applied to a prefix via the same command style
![2018-05-13 14_08_02-minecraft 1 12 2](https://user-images.githubusercontent.com/6345469/39970788-5f079ade-56b7-11e8-9d54-f532dc7218e9.png)

it does not seem to work. It saves it correctly, but the prefix never loads if set this way.
![2018-05-13 14_11_07-window](https://user-images.githubusercontent.com/6345469/39970808-97c21e44-56b7-11e8-9c26-f19051144109.png)
